"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatWidget from "@/components/ChatWidget";
import PillNav from "@/components/PillNav";
import Threads from "@/components/Threads";
import { useState, useEffect } from "react";
import Toast from "../components/Toast"; // Import the Toast component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Removed export const metadata block
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showToast, setShowToast] = useState(false);
  const [toastMessage, setToastMessage] = useState("");

  useEffect(() => {
    const handleThemeChange = () => {
      if (document.documentElement.classList.contains('dark')) {
        setToastMessage("You're saving energy!");
        setShowToast(true);
      }
    };

    const observer = new MutationObserver(handleThemeChange);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });

    return () => observer.disconnect();
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative` }>
        {/* Fixed decorative background for all pages */}
        <div className="fixed inset-0 -z-10 pointer-events-none" aria-hidden>
          <Threads amplitude={1} distance={0.8} enableMouseInteraction={false} style={{ width: '100%', height: '100%', position: 'relative' }} />
        </div>
        {/* Foreground app content */}
        <div className="relative z-0">
          <PillNav />
          {children}
          <ChatWidget />
        </div>
        <Toast message={toastMessage} show={showToast} onClose={() => setShowToast(false)} />
      </body>
    </html>
  );
}
